In [1]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))

if project_root not in sys.path:
    sys.path.append(project_root)
    print(sys.path)
from src.data.load_data import load_data

['C:\\Users\\kesu0\\AppData\\Local\\Programs\\Python\\Python314\\python314.zip', 'C:\\Users\\kesu0\\AppData\\Local\\Programs\\Python\\Python314\\DLLs', 'C:\\Users\\kesu0\\AppData\\Local\\Programs\\Python\\Python314\\Lib', 'C:\\Users\\kesu0\\AppData\\Local\\Programs\\Python\\Python314', 'c:\\Users\\kesu0\\Downloads\\ai-risk-system\\.venv', '', 'c:\\Users\\kesu0\\Downloads\\ai-risk-system\\.venv\\Lib\\site-packages', 'c:\\Users\\kesu0\\Downloads\\ai-risk-system']


In [4]:
import sys
import os
print(os.getcwd())

c:\Users\kesu0\Downloads\ai-risk-system\notebooks


In [2]:
import src.data.load_data as ld

# This will show you exactly what variables successfully loaded into that module
print(f"Available names in module: {dir(ld)}")


Available names in module: ['DATA_PATH', 'Path', 'ROOT_DIR', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'df', 'os', 'pd']


In [2]:
df = load_data("transactions.csv")
df.head()

Successfully loaded data: (284807, 31)


,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0


In [5]:
df["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [3]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df["Amount"] = sc.fit_transform(df[["Amount"]])
df["Amount"]

0         0.244964
1        -0.342475
2         1.160686
3         0.140534
4        -0.073403
            ...   
284802   -0.350151
284803   -0.254117
284804   -0.081839
284805   -0.313249
284806    0.514355
Name: Amount, Length: 284807, dtype: float64

In [4]:
df["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

X = df.iloc[:, :-1]
y= df["Class"]
print(df.shape, X.shape, y.shape)

(284807, 31) (284807, 30) (284807,)


In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify = y, random_state=2)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(227845, 30) (227845,) (56962, 30) (56962,)


In [12]:
from imblearn.over_sampling import SMOTE
from collections import Counter

# Initialize SMOTE
# SMOTE, by default, equals to the number of samples in all classes
smote = SMOTE(random_state=2)

# Fitting and transforming training data
X_smote, y_smote = smote.fit_resample(X_train, y_train)

print(f"Original distribution: {Counter(y_train)}")
print(f"SMOTE distribution: {Counter(y_smote)}")

Original distribution: Counter({0: 227451, 1: 394})
SMOTE distribution: Counter({0: 227451, 1: 227451})


In [13]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(X_smote, y_smote)

c:\Users\kesu0\Downloads\ai-risk-system\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [15]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report, confusion_matrix

y_pred = lr.predict(X_test)

print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Recall Score: ", recall_score(y_test, y_pred))
print("Precision Score: ", precision_score(y_test, y_pred))
print("F1 Score: ", f1_score(y_test, y_pred))
print("Classification Report: ", classification_report(y_test, y_pred))
print("COnfusion Matrix:\n ", confusion_matrix(y_test, y_pred))


Accuracy Score:  0.9824268810786139
Recall Score:  0.9387755102040817
Precision Score:  0.08463661453541858
F1 Score:  0.15527426160337554
Classification Report:                precision    recall  f1-score   support

           0       1.00      0.98      0.99     56864
           1       0.08      0.94      0.16        98

    accuracy                           0.98     56962
   macro avg       0.54      0.96      0.57     56962
weighted avg       1.00      0.98      0.99     56962

COnfusion Matrix:
  [[55869   995]
 [    6    92]]


In [16]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(criterion="entropy")
rf.fit(X_smote, y_smote)

y_pred = rf.predict(X_test)

print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Recall Score: ", recall_score(y_test, y_pred))
print("Precision Score: ", precision_score(y_test, y_pred))
print("F1 Score: ", f1_score(y_test, y_pred))
print("Classification Report: ", classification_report(y_test, y_pred))
print("COnfusion Matrix:\n ", confusion_matrix(y_test, y_pred))

Accuracy Score:  0.9994733330992591
Recall Score:  0.8571428571428571
Precision Score:  0.84
F1 Score:  0.8484848484848485
Classification Report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.84      0.86      0.85        98

    accuracy                           1.00     56962
   macro avg       0.92      0.93      0.92     56962
weighted avg       1.00      1.00      1.00     56962

COnfusion Matrix:
  [[56848    16]
 [   14    84]]


In [17]:
from imblearn.combine import SMOTEENN
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_recall_curve, f1_score
import numpy as np

# 1. Apply SMOTE-ENN to Training Data ONLY
sme = SMOTEENN(random_state=42)
X_res, y_res = sme.fit_resample(X_train, y_train)

# 2. Train Model
rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(X_res, y_res)

# 3. Get Probabilities for the Minority Class (Class 1)
# Use the Test set here to see how it performs on real-world data
y_probs = rf.predict_proba(X_test)[:, 1]

# 4. Calculate Precision-Recall Curve
precision, recall, thresholds = precision_recall_curve(y_test, y_probs)

# 5. Find the Optimal Threshold (Maximizing F1-Score)
# We calculate F1 for every threshold provided by the curve
f1_scores = 2 * (precision * recall) / (precision + recall + 1e-10)
ix = np.argmax(f1_scores)
best_threshold = thresholds[ix]

print(f'Best Threshold: {best_threshold:.4f}')
print(f'Best F1-Score: {f1_scores[ix]:.4f}')

# 6. Apply the New Threshold
y_pred_optimal = (y_probs >= best_threshold).astype(int)


Best Threshold: 0.5400
Best F1-Score: 0.8543


In [18]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred_optimal))


[[56848    16]
 [   13    85]]


In [27]:
from xgboost import XGBClassifier
from sklearn.metrics import precision_recall_curve
import numpy as np

# Calculating ration for ideal scale_pos_weight
ratio = int(np.sqrt(df["Class"].value_counts()[0] / df["Class"].value_counts()[1]))

xgb = XGBClassifier(
    scale_pos_weight=ratio, 
    max_delta_step=1,
    learning_rate=0.1,
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
# No need for SMOTE-ENN with scale_pos_weight
xgb.fit(X_train, y_train)
xgb_y_prob = xgb.predict_proba(X_test)[:, 1]

precision, recall, thresholds = precision_recall_curve(y_test, xgb_y_prob)
f1_score = 2*(precision * recall) / (precision + recall + 1e-10)
best_index = np.argmax(f1_score)
best_threshold = thresholds[best_index]

print(f"Optimal Threshold: {best_threshold:.4f}")
print(f"Best F1-Score: {f1_score[best_index]:.4f}")

y_pred_optimal = (y_probs >= best_threshold).astype(int)


Optimal Threshold: 0.9291
Best F1-Score: 0.8817


In [31]:
from lightgbm import LGBMClassifier
from sklearn.metrics import precision_recall_curve
import numpy as np

# Calculating ration for ideal scale_pos_weight
ratio = int(np.sqrt(df["Class"].value_counts()[0] / df["Class"].value_counts()[1]))

lgbm = LGBMClassifier()

lgbm.fit(X_smote, y_smote)
lgbm_y_prob = lgbm.predict_proba(X_test)[:, 1]

precision, recall, thresholds = precision_recall_curve(y_test, lgbm_y_prob)
f1_score = 2*(precision * recall) / (precision + recall + 1e-10)
best_index = np.argmax(f1_score)
best_threshold = thresholds[best_index]

print(f"Optimal Threshold: {best_threshold:.4f}")
print(f"Best F1-Score: {f1_score[best_index]:.4f}")

y_pred_optimal = (y_probs >= best_threshold).astype(int)


Optimal Threshold: 0.9724
Best F1-Score: 0.8469


In [29]:
print("XGBoost Confusio matrix: \n", confusion_matrix(y_test, y_pred_optimal))

XGBoost Confusio matrix: 
 [[56854    10]
 [   23    75]]


In [2]:
import os
print(os.getcwd())

c:\Users\kesu0\Downloads\ai-risk-system\notebooks


In [ ]:
import sys
from pathlib import Path

# Going up from notebooks folder to root folder
ROOT_DIR = Path().resolve().parent
sys.path.append(str(ROOT_DIR))


from src.data.load_data import load_data

df = load_data("transactions.csv")
prediction_1 = df.loc[0].to_dict()
print(prediction_1)
prediction_1.pop("Class", None)
print(prediction_1)

INFO:root:Loaded data from C:\Users\kesu0\Downloads\ai-risk-system\data\raw\transactions.csv


0.0

In [11]:
from src.models.load_model import load_model, load_scaler
import pandas as pd

# Load model and scaler
model = load_model()
scaler = load_scaler()

# Convert dict to DataFrame
input_df = pd.DataFrame([prediction_1])

# Apply SAME preprocessing
input_df["Amount"] = scaler.transform(input_df[["Amount"]])

# Predict
prediction = model.predict(input_df)[0]
probability = model.predict_proba(input_df)[0][1]

print("Prediction:", prediction)
print("Probability:", probability)

Prediction: 0
Probability: 0.01
